### ISSUE TITLE
can't find pane: 0 due to tmux setting `base-index`

### ISSUE THREAD

**Issue by vmiheer** [wrs20/tmux-mpi#6]
I totally understand if you would like to close the issue as the issue is due to custom user tmux settings. But people use the base index of tmux windows 1 so that that matches most qwerty keyboard's number ordering.
Full error:
```
Waiting for dtach sockets to appear. Found 2 out of 2.
Traceback (most recent call last):
  File "/home/mvaidya/.local/bin/tmux-mpi", line 239, in <module>
    main()
  File "/home/mvaidya/.local/bin/tmux-mpi", line 170, in main
    tmux_session.add(nproc)
  File "/home/mvaidya/.local/bin/tmux-mpi", line 78, in add
    w.select_pane("0")
  File "/home/mvaidya/.local/share/pipx/venvs/tmux-mpi/lib/python3.10/site-packages/libtmux/window.py", line 202, in select_pane
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ["can't find pane: 0"]
```

**Comment by wrs20** [comment]
Thanks for the issue. Hopefully this is fixed as of commit [1].

[1] https://github.com/wrs20/tmux-mpi/commit/6f926540b2903dd2e02d172f415042eac3c10d93

**Comment by vmiheer** [comment]
Brilliant, thank you for the fix!

Thanking you,
+miheer
